"""Rename password_hash to _password_hash

Revision ID: b1ef7517fb25
Revises: 75d7fc4bcf13
Create Date: 2024-07-17 21:38:37.690738

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b1ef7517fb25"
down_revision = "75d7fc4bcf13"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "password_hash", new_column_name="_password_hash"
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "_password_hash", new_column_name="password_hash"
        )
    # ### end Alembic commands ###
